on: push
jobs:
 first-jobs:
    runs-on: ubuntu-latest
    container: node:18
    steps:
     - run: node --version
     - run: npm version
     - uses: actions/checkout@v3
     - run: npm install
     - run: npm install ffmpeg
     - run: pkg install ffmpeg
     - run: unzip sessions.zip
     - run: node index.js
